apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lumina.name" . }}-secrets
  labels:
    {{- include "lumina.labels" . | nindent 4 }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.backend.secrets.openaiApiKey | b64enc | quote }}
  MONGO_URI: {{ .Values.backend.secrets.mongoUri | b64enc | quote }}
