apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lumina.name" . }}-secrets
  labels:
    {{- include "lumina.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  MONGO_URI: {{ .Values.secrets.mongoUri | quote }}
